apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduscheduler-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduscheduler-backend
  template:
    metadata:
      labels:
        app: eduscheduler-backend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: backend
          image: 619613970416.dkr.ecr.eu-north-1.amazonaws.com/eduscheduler-backend:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/eduscheduler
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: validate
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CORS_ALLOWED_ORIGINS
              value: "https://eduscheduler.eu,https://www.eduscheduler.eu,http://localhost:5173,http://localhost:3000"
            - name: APP_BASE_URL
              value: "https://eduscheduler.eu"
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SPRING_MAIL_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi